openapi: 3.0.3
info:
  title: Insurance Portal API
  description: Backend-for-Frontend API for the Insurance Portal
  version: 1.0.0
  contact:
    name: IRD0 Development Team

servers:
  - url: http://localhost:8090/api/portal/v1
    description: Local development server
  - url: http://portal-bff:8080/api/portal/v1
    description: Docker internal server

tags:
  - name: Dashboard
    description: Dashboard KPIs and overview
  - name: Claims
    description: Claims management
  - name: Actors
    description: Policyholders, insurers, and experts

paths:
  /dashboard:
    get:
      tags:
        - Dashboard
      summary: Get dashboard data
      operationId: getDashboard
      responses:
        '200':
          description: Dashboard data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dashboard'
        '503':
          description: Service unavailable

  /claims:
    get:
      tags:
        - Claims
      summary: List claims with filters
      operationId: getClaims
      parameters:
        - name: policyholderId
          in: query
          schema:
            type: string
            format: uuid
        - name: insurerId
          in: query
          schema:
            type: string
            format: uuid
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/ClaimStatus'
        - name: type
          in: query
          schema:
            $ref: '#/components/schemas/ClaimType'
        - name: fromDate
          in: query
          schema:
            type: string
            format: date-time
        - name: toDate
          in: query
          schema:
            type: string
            format: date-time
        - name: page
          in: query
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          schema:
            type: string
            default: createdAt,desc
      responses:
        '200':
          description: Paginated list of claims
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageClaimSummary'

    post:
      tags:
        - Claims
      summary: Create a new claim
      operationId: createClaim
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateClaimRequest'
      responses:
        '201':
          description: Claim created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimDetail'
        '400':
          description: Validation error

  /claims/{id}:
    get:
      tags:
        - Claims
      summary: Get claim detail
      operationId: getClaimById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Claim detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimDetail'
        '404':
          description: Claim not found

  /claims/{id}/status:
    put:
      tags:
        - Claims
      summary: Update claim status
      operationId: updateClaimStatus
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusUpdateRequest'
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimDetail'
        '400':
          description: Invalid status transition

  /claims/{id}/expert:
    post:
      tags:
        - Claims
      summary: Assign expert to claim
      operationId: assignExpert
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExpertAssignmentRequest'
      responses:
        '200':
          description: Expert assigned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimDetail'

  /claims/{id}/comments:
    get:
      tags:
        - Claims
      summary: Get claim comments
      operationId: getClaimComments
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'

    post:
      tags:
        - Claims
      summary: Add comment to claim
      operationId: addClaimComment
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CommentRequest'
      responses:
        '200':
          description: Comment added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClaimDetail'

  /claims/{id}/history:
    get:
      tags:
        - Claims
      summary: Get claim history
      operationId: getClaimHistory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'

  /experts:
    get:
      tags:
        - Actors
      summary: Get available experts
      operationId: getExperts
      responses:
        '200':
          description: List of experts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Actor'

  /policyholders:
    get:
      tags:
        - Actors
      summary: Get policyholders
      operationId: getPolicyholders
      responses:
        '200':
          description: List of policyholders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Actor'

  /insurers:
    get:
      tags:
        - Actors
      summary: Get insurers
      operationId: getInsurers
      responses:
        '200':
          description: List of insurers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Actor'

components:
  schemas:
    ClaimStatus:
      type: string
      enum:
        - DECLARED
        - UNDER_REVIEW
        - QUALIFIED
        - IN_PROGRESS
        - CLOSED
        - ABANDONED

    ClaimType:
      type: string
      enum:
        - WATER_DAMAGE
        - FIRE
        - THEFT
        - LIABILITY
        - PROPERTY_DAMAGE
        - NATURAL_DISASTER
        - OTHER

    Dashboard:
      type: object
      properties:
        kpis:
          $ref: '#/components/schemas/KPIs'
        statusDistribution:
          type: object
          additionalProperties:
            type: integer
            format: int64
        claimsByType:
          type: object
          additionalProperties:
            type: integer
            format: int64
        recentActivity:
          type: array
          items:
            $ref: '#/components/schemas/RecentActivity'

    KPIs:
      type: object
      properties:
        totalClaims:
          type: integer
          format: int64
        pendingCount:
          type: integer
          format: int64
        inProgressCount:
          type: integer
          format: int64
        closedThisMonth:
          type: integer
          format: int64

    RecentActivity:
      type: object
      properties:
        eventType:
          type: string
        description:
          type: string
        claimReference:
          type: string
        occurredAt:
          type: string
          format: date-time

    ClaimSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        referenceNumber:
          type: string
        status:
          $ref: '#/components/schemas/ClaimStatus'
        type:
          $ref: '#/components/schemas/ClaimType'
        policyholderName:
          type: string
        insurerName:
          type: string
        estimatedDamage:
          type: number
        currency:
          type: string
        incidentDate:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time

    ClaimDetail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        referenceNumber:
          type: string
        status:
          $ref: '#/components/schemas/ClaimStatus'
        availableTransitions:
          type: array
          items:
            $ref: '#/components/schemas/ClaimStatus'
        type:
          $ref: '#/components/schemas/ClaimType'
        description:
          type: string
        incidentDate:
          type: string
          format: date-time
        estimatedDamage:
          type: number
        currency:
          type: string
        location:
          $ref: '#/components/schemas/Location'
        policyholder:
          $ref: '#/components/schemas/Actor'
        insurer:
          $ref: '#/components/schemas/Actor'
        expertAssignments:
          type: array
          items:
            $ref: '#/components/schemas/ExpertAssignment'
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
        history:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Actor:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string

    Location:
      type: object
      properties:
        address:
          type: string
        latitude:
          type: number
        longitude:
          type: number

    ExpertAssignment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        expert:
          $ref: '#/components/schemas/Actor'
        scheduledDate:
          type: string
          format: date-time
        notes:
          type: string
        assignedAt:
          type: string
          format: date-time

    Comment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        authorId:
          type: string
          format: uuid
        authorType:
          type: string
        authorName:
          type: string
        createdAt:
          type: string
          format: date-time

    Event:
      type: object
      properties:
        id:
          type: string
          format: uuid
        eventType:
          type: string
        description:
          type: string
        oldValue:
          type: string
        newValue:
          type: string
        actorId:
          type: string
          format: uuid
        actorName:
          type: string
        occurredAt:
          type: string
          format: date-time

    CreateClaimRequest:
      type: object
      required:
        - policyholderId
        - insurerId
        - type
        - incidentDate
      properties:
        policyholderId:
          type: string
          format: uuid
        insurerId:
          type: string
          format: uuid
        type:
          $ref: '#/components/schemas/ClaimType'
        description:
          type: string
        incidentDate:
          type: string
          format: date-time
        location:
          $ref: '#/components/schemas/Location'
        estimatedDamage:
          type: number
        currency:
          type: string
          default: EUR

    StatusUpdateRequest:
      type: object
      required:
        - status
      properties:
        status:
          $ref: '#/components/schemas/ClaimStatus'
        reason:
          type: string

    ExpertAssignmentRequest:
      type: object
      required:
        - expertId
      properties:
        expertId:
          type: string
          format: uuid
        scheduledDate:
          type: string
          format: date-time
        notes:
          type: string

    CommentRequest:
      type: object
      required:
        - content
        - authorId
        - authorType
      properties:
        content:
          type: string
        authorId:
          type: string
          format: uuid
        authorType:
          type: string

    PageClaimSummary:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ClaimSummary'
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
        size:
          type: integer
        number:
          type: integer
