openapi: 3.1.0
info:
  title: Insurance Portal API
  description: Backend-for-Frontend API for the Insurance Portal
  contact:
    name: IRD0 Development Team
  version: 1.0.0
servers:
- url: http://localhost:7777
  description: API Server
tags:
- name: Actors
  description: "Policyholders, insurers, and experts"
- name: Claims
  description: Claims management operations
- name: Dashboard
  description: Dashboard KPIs and overview
paths:
  /api/portal/v1/claims/{id}/status:
    put:
      tags:
      - Claims
      summary: Update claim status
      operationId: updateClaimStatus
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StatusUpdateRequestDTO"
        required: true
      responses:
        "200":
          description: Status updated
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClaimDetailDTO"
  /api/portal/v1/claims:
    get:
      tags:
      - Claims
      summary: List claims with filters
      operationId: getClaims
      parameters:
      - name: policyholderId
        in: query
        required: false
        schema:
          type: string
          format: uuid
      - name: insurerId
        in: query
        required: false
        schema:
          type: string
          format: uuid
      - name: status
        in: query
        required: false
        schema:
          type: string
      - name: type
        in: query
        required: false
        schema:
          type: string
      - name: fromDate
        in: query
        required: false
        schema:
          type: string
          format: date-time
      - name: toDate
        in: query
        required: false
        schema:
          type: string
          format: date-time
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 20
      - name: sort
        in: query
        required: false
        schema:
          type: string
          default: "createdAt,desc"
      responses:
        "200":
          description: Paginated list of claims
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/PageClaimSummaryDTO"
    post:
      tags:
      - Claims
      summary: Create new claim
      operationId: createClaim
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateClaimRequestDTO"
        required: true
      responses:
        "201":
          description: Claim created
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClaimDetailDTO"
  /api/portal/v1/claims/{id}/expert:
    post:
      tags:
      - Claims
      summary: Assign expert to claim
      operationId: assignExpert
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpertAssignmentRequestDTO"
        required: true
      responses:
        "200":
          description: Expert assigned
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClaimDetailDTO"
  /api/portal/v1/claims/{id}/comments:
    get:
      tags:
      - Claims
      summary: Get claim comments
      operationId: getClaimComments
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: List of comments
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CommentDTO"
    post:
      tags:
      - Claims
      summary: Add comment to claim
      operationId: addClaimComment
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommentRequestDTO"
        required: true
      responses:
        "200":
          description: Comment added
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClaimDetailDTO"
  /api/portal/v1/policyholders:
    get:
      tags:
      - Claims
      - Actors
      summary: Get policyholders list
      operationId: getPolicyholders
      responses:
        "200":
          description: List of policyholders
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActorDTO"
  /api/portal/v1/insurers:
    get:
      tags:
      - Claims
      - Actors
      summary: Get insurers list
      operationId: getInsurers
      responses:
        "200":
          description: List of insurers
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActorDTO"
  /api/portal/v1/experts:
    get:
      tags:
      - Claims
      - Actors
      summary: Get available experts
      operationId: getExperts
      responses:
        "200":
          description: List of experts
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ActorDTO"
  /api/portal/v1/dashboard:
    get:
      tags:
      - Dashboard
      summary: Get dashboard data
      operationId: getDashboard
      responses:
        "200":
          description: Dashboard KPIs and statistics
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DashboardDTO"
  /api/portal/v1/claims/{id}:
    get:
      tags:
      - Claims
      summary: Get claim by ID
      operationId: getClaimById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "404":
          description: Claim not found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClaimDetailDTO"
        "200":
          description: Claim found
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ClaimDetailDTO"
  /api/portal/v1/claims/{id}/history:
    get:
      tags:
      - Claims
      summary: Get claim event history
      operationId: getClaimHistory
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: Event history
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EventDTO"
components:
  schemas:
    StatusUpdateRequestDTO:
      type: object
      properties:
        status:
          type: string
        reason:
          type: string
      required:
      - status
    ActorDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        type:
          type: string
        email:
          type: string
        phone:
          type: string
        address:
          type: string
    ClaimDetailDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        referenceNumber:
          type: string
        status:
          type: string
        availableTransitions:
          type: array
          items:
            type: string
        type:
          type: string
        description:
          type: string
        incidentDate:
          type: string
          format: date-time
        estimatedDamage:
          type: number
        currency:
          type: string
        location:
          $ref: "#/components/schemas/LocationDTO"
        policyholder:
          $ref: "#/components/schemas/ActorDTO"
        insurer:
          $ref: "#/components/schemas/ActorDTO"
        expertAssignments:
          type: array
          items:
            $ref: "#/components/schemas/ExpertAssignmentDTO"
        comments:
          type: array
          items:
            $ref: "#/components/schemas/CommentDTO"
        history:
          type: array
          items:
            $ref: "#/components/schemas/EventDTO"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    CommentDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        content:
          type: string
        authorId:
          type: string
          format: uuid
        authorType:
          type: string
        authorName:
          type: string
        createdAt:
          type: string
          format: date-time
    EventDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        eventType:
          type: string
        description:
          type: string
        oldValue:
          type: string
        newValue:
          type: string
        actorId:
          type: string
          format: uuid
        actorName:
          type: string
        occurredAt:
          type: string
          format: date-time
    ExpertAssignmentDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        expert:
          $ref: "#/components/schemas/ActorDTO"
        scheduledDate:
          type: string
          format: date-time
        notes:
          type: string
        assignedAt:
          type: string
          format: date-time
    LocationDTO:
      type: object
      properties:
        address:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
    CreateClaimRequestDTO:
      type: object
      properties:
        policyholderId:
          type: string
          format: uuid
        insurerId:
          type: string
          format: uuid
        type:
          type: string
        description:
          type: string
        incidentDate:
          type: string
          format: date-time
        location:
          $ref: "#/components/schemas/LocationDTO"
        estimatedDamage:
          type: number
        currency:
          type: string
      required:
      - incidentDate
      - insurerId
      - policyholderId
      - type
    ExpertAssignmentRequestDTO:
      type: object
      properties:
        expertId:
          type: string
          format: uuid
        scheduledDate:
          type: string
          format: date-time
        notes:
          type: string
      required:
      - expertId
    CommentRequestDTO:
      type: object
      properties:
        content:
          type: string
        authorId:
          type: string
          format: uuid
        authorType:
          type: string
      required:
      - authorId
      - authorType
      - content
    DashboardDTO:
      type: object
      properties:
        kpis:
          $ref: "#/components/schemas/KpiDTO"
        statusDistribution:
          type: object
          additionalProperties:
            type: integer
            format: int64
        claimsByType:
          type: object
          additionalProperties:
            type: integer
            format: int64
        recentActivity:
          type: array
          items:
            $ref: "#/components/schemas/RecentActivityDTO"
    KpiDTO:
      type: object
      properties:
        totalClaims:
          type: integer
          format: int64
        pendingCount:
          type: integer
          format: int64
        inProgressCount:
          type: integer
          format: int64
        closedThisMonth:
          type: integer
          format: int64
    RecentActivityDTO:
      type: object
      properties:
        eventType:
          type: string
        description:
          type: string
        claimReference:
          type: string
        occurredAt:
          type: string
          format: date-time
    ClaimSummaryDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        referenceNumber:
          type: string
        status:
          type: string
        type:
          type: string
        policyholderName:
          type: string
        insurerName:
          type: string
        estimatedDamage:
          type: number
        currency:
          type: string
        incidentDate:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
    PageClaimSummaryDTO:
      type: object
      properties:
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
          format: int32
        pageable:
          $ref: "#/components/schemas/PageableObject"
        first:
          type: boolean
        last:
          type: boolean
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: "#/components/schemas/ClaimSummaryDTO"
        number:
          type: integer
          format: int32
        sort:
          $ref: "#/components/schemas/SortObject"
        numberOfElements:
          type: integer
          format: int32
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        paged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        offset:
          type: integer
          format: int64
        sort:
          $ref: "#/components/schemas/SortObject"
        unpaged:
          type: boolean
    SortObject:
      type: object
      properties:
        sorted:
          type: boolean
        empty:
          type: boolean
        unsorted:
          type: boolean
